version: '3'
services:
  mongo:
    image: mongo:4.0.5
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    restart: always

  wishlist_service:
    image: wishlist-service_catalog_service:latest
    build:
      context: wishlist-service
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 8081:8081

  user_service:
    image: user-service_catalog_service:latest
    build:
      context: user-service
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 9001:9001

volumes:
  mongodb:
