apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
  namespace: default
data:
  MONGO_HOST: mongo
  MONGO_PORT: "27017"
  PRODUCT_SERVICE: catalog-service
  WISHLIST_SERVICE: wishlist-service
