apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  labels:
    app: wishlist-service
spec:
  ports:
  - port: 9001
    targetPort: 9001
  type: NodePort
  selector:
    app: wishlist-service
