apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-service
  labels:
    app: wishlist-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wishlist-service
  template:
    metadata:
      labels:
        app: wishlist-service
    spec:
      containers:
      - name: wishlist-service
        image: wishlist-service_catalog_service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: Always
