apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  labels:
    app: wishlist-service
spec:
  containers:
    envFrom:
    - configMapRef:
      name: env-configmap
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app: wishlist-service
